### ISSUE TITLE
로그인 기능 에러

### ISSUE THREAD

**Issue by minji-kim525** [minji-kim525/team-project#15]
## 이슈 내용
- app.py 로그인 기능 에러
```python
token = jwt.encode(payload, SECRET_KEY, algorithm='HS256').decode('utf-8')
```
 pyjwt 기존 버전에서 ```jwt.encode() ```함수의 리턴값인 바이트 문자열을```.decode('utf-8')```를 붙여 일반 문자열로 바꾸어주는 코드
2.0.0 버전부터는  ```jwt.encode() ```의 리턴값이 일반 문자열이기 때문에 ```.decode('utf-8')```를 붙이면 에러 발생

## 해결 방법
```python
token = jwt.encode(payload, SECRET_KEY, algorithm='HS256')
```
로 바꾸기 or 
jwt 2.0.0 버전을 다운그레이드

**Comment by HayeonKimm** [comment]
잘 정리하셨네요 ~!!! 정리 감사합니다 !
