### ISSUE TITLE
버튼 스타일+ 호버값 공유 

### ISSUE THREAD

**Issue by ins62o** [minji-kim525/team-project#16]
.button-style {
  padding: 14px 32px;
  background-color: #1ed760;
  border-radius: 500px;
  font-size: inherit;
  color: #2941ab;
  font-weight: 700;
  border: none;
}

.button-style:hover {
  transform: scale(1.07);
}

**Comment by HayeonKimm** [comment]
확인했습니다 올려주셔서 감사해요!!!
