### ISSUE TITLE
Branch main의 app.py 파일 삭제 건의 

### ISSUE THREAD

**Issue by HayeonKimm** [minji-kim525/team-project#7]
Branch main의 app.py 파일 삭제 건의 드립니다 !

없어도 될 것 같은데 혹시 인성님이 지워주실 수 있을까요 ?

**Comment by ins62o** [comment]
삭제 완료 했습니다 !

**Comment by HayeonKimm** [comment]
> 삭제 완료 했습니다 !

감사합니다 인성님 !! 이슈 닫겠습니다 :)
